version: 2
updates:
  - package-ecosystem: "cargo"
    commit-message:
      prefix: "📌"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    commit-message:
      prefix: "📌"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
 